spring:
  datasource:
    url: jdbc-secretsmanager:mysql://host:port/port
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    username: username
    password: username
    validation-query: SELECT 1
#spring.datasource.url=jdbc-secretsmanager:mysql://test/secret/
#spring.datasource.username=test/secret/
#spring.datasource.driver-class-name=com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
#spring.datasource.validation-query=SELECT 1
    
  jpa:
    spring.jpa.database-platform : org.hibernate.dialect.MySQL8Dialect
    h2 : 
       database-platform: org.hibernate.dialect.H2Dialect 
    show-sql  : true
    hibernate:
           ddl-auto : update

management:
  endpoint:
    health:
      show-details: always
aws:
    secretsmanager:
        name: prod/rds/mysql      
cloud:
  aws:
    region:
      static: us-east-1
      endpoint: https://secretsmanager.us-east-1.amazonaws.com
      cache-ttl: 3600