spring:
  datasource:
    url: jdbc:mysql://book-db-instance.cw8jcq9o5fxc.us-east-1.rds.amazonaws.com:3306/book_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: Lalp0xddNaVMauRM6qys
#spring.datasource.url=jdbc-secretsmanager:mysql://test/secret/
#spring.datasource.username=test/secret/
#spring.datasource.driver-class-name=com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
#spring.datasource.validation-query=SELECT 1
    
  jpa:
    spring.jpa.database-platform : org.hibernate.dialect.MySQL8Dialect
    h2 : 
       database-platform: org.hibernate.dialect.H2Dialect 
    show-sql  : true
    hibernate:
           ddl-auto : update

management:
  endpoint:
    health:
      show-details: always
