spring:
#  profiles:
#    active: prod
  datasource:
    url: jdbc:mysql://book-db-instance.cw8jcq9o5fxc.us-east-1.rds.amazonaws.com:3306/book_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: Lalp0xddNaVMauRM6qys
  jpa:
    spring.jpa.database-platform : org.hibernate.dialect.MySQL8Dialect
    show-sql  : true
    hibernate:
           ddl-auto : update

management:
  endpoint:
    health:
      show-details: always
