spring:
#  config: 
#    import: aws/secretsmanager:prod/rds/mysql
 # datasource:
  #  url: jdbc-secretsmanager:mysql://host:port/dbname
 #   driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver  
 #   username: username
 #   password: password
  jpa:
    spring.jpa.database-platform : org.hibernate.dialect.MySQL8Dialect
    h2 : 
       database-platform: org.hibernate.dialect.H2Dialect 
    show-sql  : true
    hibernate:
           ddl-auto : update

management:
  endpoint:
    health:
      show-details: always
